module StripeAPI.Types.AccountFutureRequirements where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data AccountFutureRequirements
instance Show AccountFutureRequirements
instance Eq AccountFutureRequirements
instance FromJSON AccountFutureRequirements
instance ToJSON AccountFutureRequirements
