{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema InvoicePaymentMethodOptionsAcssDebitMandateOptions
module StripeAPI.Types.InvoicePaymentMethodOptionsAcssDebitMandateOptions where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.invoice_payment_method_options_acss_debit_mandate_options@ in the specification.
data InvoicePaymentMethodOptionsAcssDebitMandateOptions = InvoicePaymentMethodOptionsAcssDebitMandateOptions
  { -- | transaction_type: Transaction type of the mandate.
    invoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType :: (GHC.Maybe.Maybe InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType')
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON InvoicePaymentMethodOptionsAcssDebitMandateOptions where
  toJSON obj = Data.Aeson.Types.Internal.object ("transaction_type" Data.Aeson.Types.ToJSON..= invoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType obj : GHC.Base.mempty)
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs ("transaction_type" Data.Aeson.Types.ToJSON..= invoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType obj)

instance Data.Aeson.Types.FromJSON.FromJSON InvoicePaymentMethodOptionsAcssDebitMandateOptions where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "InvoicePaymentMethodOptionsAcssDebitMandateOptions" (\obj -> GHC.Base.pure InvoicePaymentMethodOptionsAcssDebitMandateOptions GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "transaction_type"))

-- | Create a new 'InvoicePaymentMethodOptionsAcssDebitMandateOptions' with all required fields.
mkInvoicePaymentMethodOptionsAcssDebitMandateOptions :: InvoicePaymentMethodOptionsAcssDebitMandateOptions
mkInvoicePaymentMethodOptionsAcssDebitMandateOptions = InvoicePaymentMethodOptionsAcssDebitMandateOptions {invoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType = GHC.Maybe.Nothing}

-- | Defines the enum schema located at @components.schemas.invoice_payment_method_options_acss_debit_mandate_options.properties.transaction_type@ in the specification.
--
-- Transaction type of the mandate.
data InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"business"@
    InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'EnumBusiness
  | -- | Represents the JSON value @"personal"@
    InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'EnumPersonal
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType' where
  toJSON (InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'Other val) = val
  toJSON (InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'EnumBusiness) = "business"
  toJSON (InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'EnumPersonal) = "personal"

instance Data.Aeson.Types.FromJSON.FromJSON InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType' where
  parseJSON val =
    GHC.Base.pure
      ( if
            | val GHC.Classes.== "business" -> InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'EnumBusiness
            | val GHC.Classes.== "personal" -> InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'EnumPersonal
            | GHC.Base.otherwise -> InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'Other val
      )
