module StripeAPI.Types.InvoicePaymentMethodOptionsAcssDebitMandateOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance Show InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance Eq InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance FromJSON InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance ToJSON InvoicePaymentMethodOptionsAcssDebitMandateOptions
data InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'
instance Show InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'
instance Eq InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'
instance FromJSON InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'
instance ToJSON InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'
