{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema IssuingCardGooglePay
module StripeAPI.Types.IssuingCardGooglePay where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.issuing_card_google_pay@ in the specification.
data IssuingCardGooglePay = IssuingCardGooglePay
  { -- | eligible: Google Pay Eligibility
    issuingCardGooglePayEligible :: GHC.Types.Bool,
    -- | ineligible_reason: Reason the card is ineligible for Google Pay
    issuingCardGooglePayIneligibleReason :: (GHC.Maybe.Maybe IssuingCardGooglePayIneligibleReason')
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON IssuingCardGooglePay where
  toJSON obj = Data.Aeson.Types.Internal.object ("eligible" Data.Aeson.Types.ToJSON..= issuingCardGooglePayEligible obj : "ineligible_reason" Data.Aeson.Types.ToJSON..= issuingCardGooglePayIneligibleReason obj : GHC.Base.mempty)
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("eligible" Data.Aeson.Types.ToJSON..= issuingCardGooglePayEligible obj) GHC.Base.<> ("ineligible_reason" Data.Aeson.Types.ToJSON..= issuingCardGooglePayIneligibleReason obj))

instance Data.Aeson.Types.FromJSON.FromJSON IssuingCardGooglePay where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "IssuingCardGooglePay" (\obj -> (GHC.Base.pure IssuingCardGooglePay GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "eligible")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "ineligible_reason"))

-- | Create a new 'IssuingCardGooglePay' with all required fields.
mkIssuingCardGooglePay ::
  -- | 'issuingCardGooglePayEligible'
  GHC.Types.Bool ->
  IssuingCardGooglePay
mkIssuingCardGooglePay issuingCardGooglePayEligible =
  IssuingCardGooglePay
    { issuingCardGooglePayEligible = issuingCardGooglePayEligible,
      issuingCardGooglePayIneligibleReason = GHC.Maybe.Nothing
    }

-- | Defines the enum schema located at @components.schemas.issuing_card_google_pay.properties.ineligible_reason@ in the specification.
--
-- Reason the card is ineligible for Google Pay
data IssuingCardGooglePayIneligibleReason'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    IssuingCardGooglePayIneligibleReason'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    IssuingCardGooglePayIneligibleReason'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"missing_agreement"@
    IssuingCardGooglePayIneligibleReason'EnumMissingAgreement
  | -- | Represents the JSON value @"missing_cardholder_contact"@
    IssuingCardGooglePayIneligibleReason'EnumMissingCardholderContact
  | -- | Represents the JSON value @"unsupported_region"@
    IssuingCardGooglePayIneligibleReason'EnumUnsupportedRegion
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON IssuingCardGooglePayIneligibleReason' where
  toJSON (IssuingCardGooglePayIneligibleReason'Other val) = val
  toJSON (IssuingCardGooglePayIneligibleReason'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (IssuingCardGooglePayIneligibleReason'EnumMissingAgreement) = "missing_agreement"
  toJSON (IssuingCardGooglePayIneligibleReason'EnumMissingCardholderContact) = "missing_cardholder_contact"
  toJSON (IssuingCardGooglePayIneligibleReason'EnumUnsupportedRegion) = "unsupported_region"

instance Data.Aeson.Types.FromJSON.FromJSON IssuingCardGooglePayIneligibleReason' where
  parseJSON val =
    GHC.Base.pure
      ( if
            | val GHC.Classes.== "missing_agreement" -> IssuingCardGooglePayIneligibleReason'EnumMissingAgreement
            | val GHC.Classes.== "missing_cardholder_contact" -> IssuingCardGooglePayIneligibleReason'EnumMissingCardholderContact
            | val GHC.Classes.== "unsupported_region" -> IssuingCardGooglePayIneligibleReason'EnumUnsupportedRegion
            | GHC.Base.otherwise -> IssuingCardGooglePayIneligibleReason'Other val
      )
