module StripeAPI.Types.PaymentPagesCheckoutSessionAfterExpirationRecovery where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentPagesCheckoutSessionAfterExpirationRecovery
instance Show PaymentPagesCheckoutSessionAfterExpirationRecovery
instance Eq PaymentPagesCheckoutSessionAfterExpirationRecovery
instance FromJSON PaymentPagesCheckoutSessionAfterExpirationRecovery
instance ToJSON PaymentPagesCheckoutSessionAfterExpirationRecovery
