{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PaymentMethodOptionsKlarna
module StripeAPI.Types.PaymentMethodOptionsKlarna where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.payment_method_options_klarna@ in the specification.
data PaymentMethodOptionsKlarna = PaymentMethodOptionsKlarna
  { -- | preferred_locale: Preferred locale of the Klarna checkout page that the customer is redirected to.
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    paymentMethodOptionsKlarnaPreferredLocale :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PaymentMethodOptionsKlarna where
  toJSON obj = Data.Aeson.Types.Internal.object ("preferred_locale" Data.Aeson.Types.ToJSON..= paymentMethodOptionsKlarnaPreferredLocale obj : GHC.Base.mempty)
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs ("preferred_locale" Data.Aeson.Types.ToJSON..= paymentMethodOptionsKlarnaPreferredLocale obj)

instance Data.Aeson.Types.FromJSON.FromJSON PaymentMethodOptionsKlarna where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentMethodOptionsKlarna" (\obj -> GHC.Base.pure PaymentMethodOptionsKlarna GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "preferred_locale"))

-- | Create a new 'PaymentMethodOptionsKlarna' with all required fields.
mkPaymentMethodOptionsKlarna :: PaymentMethodOptionsKlarna
mkPaymentMethodOptionsKlarna = PaymentMethodOptionsKlarna {paymentMethodOptionsKlarnaPreferredLocale = GHC.Maybe.Nothing}
