module StripeAPI.Types.PaymentPagesCheckoutSessionPhoneNumberCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentPagesCheckoutSessionPhoneNumberCollection
instance Show PaymentPagesCheckoutSessionPhoneNumberCollection
instance Eq PaymentPagesCheckoutSessionPhoneNumberCollection
instance FromJSON PaymentPagesCheckoutSessionPhoneNumberCollection
instance ToJSON PaymentPagesCheckoutSessionPhoneNumberCollection
