module StripeAPI.Types.PaymentPagesCheckoutSessionAfterExpiration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentPagesCheckoutSessionAfterExpiration
instance Show PaymentPagesCheckoutSessionAfterExpiration
instance Eq PaymentPagesCheckoutSessionAfterExpiration
instance FromJSON PaymentPagesCheckoutSessionAfterExpiration
instance ToJSON PaymentPagesCheckoutSessionAfterExpiration
data PaymentPagesCheckoutSessionAfterExpirationRecovery'
instance Show PaymentPagesCheckoutSessionAfterExpirationRecovery'
instance Eq PaymentPagesCheckoutSessionAfterExpirationRecovery'
instance FromJSON PaymentPagesCheckoutSessionAfterExpirationRecovery'
instance ToJSON PaymentPagesCheckoutSessionAfterExpirationRecovery'
