module StripeAPI.Types.PaymentPagesCheckoutSessionConsentCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentPagesCheckoutSessionConsentCollection
instance Show PaymentPagesCheckoutSessionConsentCollection
instance Eq PaymentPagesCheckoutSessionConsentCollection
instance FromJSON PaymentPagesCheckoutSessionConsentCollection
instance ToJSON PaymentPagesCheckoutSessionConsentCollection
data PaymentPagesCheckoutSessionConsentCollectionPromotions'
instance Show PaymentPagesCheckoutSessionConsentCollectionPromotions'
instance Eq PaymentPagesCheckoutSessionConsentCollectionPromotions'
instance FromJSON PaymentPagesCheckoutSessionConsentCollectionPromotions'
instance ToJSON PaymentPagesCheckoutSessionConsentCollectionPromotions'
