module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsKlarnaDob where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentFlowsPrivatePaymentMethodsKlarnaDob
instance Show PaymentFlowsPrivatePaymentMethodsKlarnaDob
instance Eq PaymentFlowsPrivatePaymentMethodsKlarnaDob
instance FromJSON PaymentFlowsPrivatePaymentMethodsKlarnaDob
instance ToJSON PaymentFlowsPrivatePaymentMethodsKlarnaDob
