{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema QuotesResourceComputed
module StripeAPI.Types.QuotesResourceComputed where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.QuotesResourceRecurring
import {-# SOURCE #-} StripeAPI.Types.QuotesResourceTotalDetails
import {-# SOURCE #-} StripeAPI.Types.QuotesResourceUpfront
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.quotes_resource_computed@ in the specification.
data QuotesResourceComputed = QuotesResourceComputed
  { -- | recurring: The definitive totals and line items the customer will be charged on a recurring basis. Takes into account the line items with recurring prices and discounts with \`duration=forever\` coupons only. Defaults to \`null\` if no inputted line items with recurring prices.
    quotesResourceComputedRecurring :: (GHC.Maybe.Maybe QuotesResourceComputedRecurring'),
    -- | upfront:
    quotesResourceComputedUpfront :: QuotesResourceUpfront
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON QuotesResourceComputed where
  toJSON obj = Data.Aeson.Types.Internal.object ("recurring" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring obj : "upfront" Data.Aeson.Types.ToJSON..= quotesResourceComputedUpfront obj : GHC.Base.mempty)
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("recurring" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring obj) GHC.Base.<> ("upfront" Data.Aeson.Types.ToJSON..= quotesResourceComputedUpfront obj))

instance Data.Aeson.Types.FromJSON.FromJSON QuotesResourceComputed where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "QuotesResourceComputed" (\obj -> (GHC.Base.pure QuotesResourceComputed GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "recurring")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "upfront"))

-- | Create a new 'QuotesResourceComputed' with all required fields.
mkQuotesResourceComputed ::
  -- | 'quotesResourceComputedUpfront'
  QuotesResourceUpfront ->
  QuotesResourceComputed
mkQuotesResourceComputed quotesResourceComputedUpfront =
  QuotesResourceComputed
    { quotesResourceComputedRecurring = GHC.Maybe.Nothing,
      quotesResourceComputedUpfront = quotesResourceComputedUpfront
    }

-- | Defines the object schema located at @components.schemas.quotes_resource_computed.properties.recurring.anyOf@ in the specification.
--
-- The definitive totals and line items the customer will be charged on a recurring basis. Takes into account the line items with recurring prices and discounts with \\\`duration=forever\\\` coupons only. Defaults to \\\`null\\\` if no inputted line items with recurring prices.
data QuotesResourceComputedRecurring' = QuotesResourceComputedRecurring'
  { -- | amount_subtotal: Total before any discounts or taxes are applied.
    quotesResourceComputedRecurring'AmountSubtotal :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | amount_total: Total after discounts and taxes are applied.
    quotesResourceComputedRecurring'AmountTotal :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | interval: The frequency at which a subscription is billed. One of \`day\`, \`week\`, \`month\` or \`year\`.
    quotesResourceComputedRecurring'Interval :: (GHC.Maybe.Maybe QuotesResourceComputedRecurring'Interval'),
    -- | interval_count: The number of intervals (specified in the \`interval\` attribute) between subscription billings. For example, \`interval=month\` and \`interval_count=3\` bills every 3 months.
    quotesResourceComputedRecurring'IntervalCount :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | total_details:
    quotesResourceComputedRecurring'TotalDetails :: (GHC.Maybe.Maybe QuotesResourceTotalDetails)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON QuotesResourceComputedRecurring' where
  toJSON obj = Data.Aeson.Types.Internal.object ("amount_subtotal" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'AmountSubtotal obj : "amount_total" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'AmountTotal obj : "interval" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'Interval obj : "interval_count" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'IntervalCount obj : "total_details" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'TotalDetails obj : GHC.Base.mempty)
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("amount_subtotal" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'AmountSubtotal obj) GHC.Base.<> (("amount_total" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'AmountTotal obj) GHC.Base.<> (("interval" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'Interval obj) GHC.Base.<> (("interval_count" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'IntervalCount obj) GHC.Base.<> ("total_details" Data.Aeson.Types.ToJSON..= quotesResourceComputedRecurring'TotalDetails obj)))))

instance Data.Aeson.Types.FromJSON.FromJSON QuotesResourceComputedRecurring' where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "QuotesResourceComputedRecurring'" (\obj -> ((((GHC.Base.pure QuotesResourceComputedRecurring' GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "amount_subtotal")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "amount_total")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "interval")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "interval_count")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "total_details"))

-- | Create a new 'QuotesResourceComputedRecurring'' with all required fields.
mkQuotesResourceComputedRecurring' :: QuotesResourceComputedRecurring'
mkQuotesResourceComputedRecurring' =
  QuotesResourceComputedRecurring'
    { quotesResourceComputedRecurring'AmountSubtotal = GHC.Maybe.Nothing,
      quotesResourceComputedRecurring'AmountTotal = GHC.Maybe.Nothing,
      quotesResourceComputedRecurring'Interval = GHC.Maybe.Nothing,
      quotesResourceComputedRecurring'IntervalCount = GHC.Maybe.Nothing,
      quotesResourceComputedRecurring'TotalDetails = GHC.Maybe.Nothing
    }

-- | Defines the enum schema located at @components.schemas.quotes_resource_computed.properties.recurring.anyOf.properties.interval@ in the specification.
--
-- The frequency at which a subscription is billed. One of \`day\`, \`week\`, \`month\` or \`year\`.
data QuotesResourceComputedRecurring'Interval'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    QuotesResourceComputedRecurring'Interval'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    QuotesResourceComputedRecurring'Interval'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"day"@
    QuotesResourceComputedRecurring'Interval'EnumDay
  | -- | Represents the JSON value @"month"@
    QuotesResourceComputedRecurring'Interval'EnumMonth
  | -- | Represents the JSON value @"week"@
    QuotesResourceComputedRecurring'Interval'EnumWeek
  | -- | Represents the JSON value @"year"@
    QuotesResourceComputedRecurring'Interval'EnumYear
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON QuotesResourceComputedRecurring'Interval' where
  toJSON (QuotesResourceComputedRecurring'Interval'Other val) = val
  toJSON (QuotesResourceComputedRecurring'Interval'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (QuotesResourceComputedRecurring'Interval'EnumDay) = "day"
  toJSON (QuotesResourceComputedRecurring'Interval'EnumMonth) = "month"
  toJSON (QuotesResourceComputedRecurring'Interval'EnumWeek) = "week"
  toJSON (QuotesResourceComputedRecurring'Interval'EnumYear) = "year"

instance Data.Aeson.Types.FromJSON.FromJSON QuotesResourceComputedRecurring'Interval' where
  parseJSON val =
    GHC.Base.pure
      ( if
            | val GHC.Classes.== "day" -> QuotesResourceComputedRecurring'Interval'EnumDay
            | val GHC.Classes.== "month" -> QuotesResourceComputedRecurring'Interval'EnumMonth
            | val GHC.Classes.== "week" -> QuotesResourceComputedRecurring'Interval'EnumWeek
            | val GHC.Classes.== "year" -> QuotesResourceComputedRecurring'Interval'EnumYear
            | GHC.Base.otherwise -> QuotesResourceComputedRecurring'Interval'Other val
      )
