module StripeAPI.Types.SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
instance FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
instance ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
instance FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
instance ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
