module StripeAPI.Types.ShippingRateFixedAmount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data ShippingRateFixedAmount
instance Show ShippingRateFixedAmount
instance Eq ShippingRateFixedAmount
instance FromJSON ShippingRateFixedAmount
instance ToJSON ShippingRateFixedAmount
