{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema SubscriptionsResourcePaymentMethodOptions
module StripeAPI.Types.SubscriptionsResourcePaymentMethodOptions where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.InvoicePaymentMethodOptionsAcssDebit
import {-# SOURCE #-} StripeAPI.Types.InvoicePaymentMethodOptionsAcssDebitMandateOptions
import {-# SOURCE #-} StripeAPI.Types.InvoicePaymentMethodOptionsBancontact
import {-# SOURCE #-} StripeAPI.Types.SubscriptionPaymentMethodOptionsCard
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.subscriptions_resource_payment_method_options@ in the specification.
data SubscriptionsResourcePaymentMethodOptions = SubscriptionsResourcePaymentMethodOptions
  { -- | acss_debit: This sub-hash contains details about the Canadian pre-authorized debit payment method options to pass to invoices created by the subscription.
    subscriptionsResourcePaymentMethodOptionsAcssDebit :: (GHC.Maybe.Maybe SubscriptionsResourcePaymentMethodOptionsAcssDebit'),
    -- | bancontact: This sub-hash contains details about the Bancontact payment method options to pass to invoices created by the subscription.
    subscriptionsResourcePaymentMethodOptionsBancontact :: (GHC.Maybe.Maybe SubscriptionsResourcePaymentMethodOptionsBancontact'),
    -- | card: This sub-hash contains details about the Card payment method options to pass to invoices created by the subscription.
    subscriptionsResourcePaymentMethodOptionsCard :: (GHC.Maybe.Maybe SubscriptionsResourcePaymentMethodOptionsCard')
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionsResourcePaymentMethodOptions where
  toJSON obj = Data.Aeson.Types.Internal.object ("acss_debit" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsAcssDebit obj : "bancontact" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsBancontact obj : "card" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsCard obj : GHC.Base.mempty)
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("acss_debit" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsAcssDebit obj) GHC.Base.<> (("bancontact" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsBancontact obj) GHC.Base.<> ("card" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsCard obj)))

instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionsResourcePaymentMethodOptions where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "SubscriptionsResourcePaymentMethodOptions" (\obj -> ((GHC.Base.pure SubscriptionsResourcePaymentMethodOptions GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "acss_debit")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "bancontact")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "card"))

-- | Create a new 'SubscriptionsResourcePaymentMethodOptions' with all required fields.
mkSubscriptionsResourcePaymentMethodOptions :: SubscriptionsResourcePaymentMethodOptions
mkSubscriptionsResourcePaymentMethodOptions =
  SubscriptionsResourcePaymentMethodOptions
    { subscriptionsResourcePaymentMethodOptionsAcssDebit = GHC.Maybe.Nothing,
      subscriptionsResourcePaymentMethodOptionsBancontact = GHC.Maybe.Nothing,
      subscriptionsResourcePaymentMethodOptionsCard = GHC.Maybe.Nothing
    }

-- | Defines the object schema located at @components.schemas.subscriptions_resource_payment_method_options.properties.acss_debit.anyOf@ in the specification.
--
-- This sub-hash contains details about the Canadian pre-authorized debit payment method options to pass to invoices created by the subscription.
data SubscriptionsResourcePaymentMethodOptionsAcssDebit' = SubscriptionsResourcePaymentMethodOptionsAcssDebit'
  { -- | mandate_options:
    subscriptionsResourcePaymentMethodOptionsAcssDebit'MandateOptions :: (GHC.Maybe.Maybe InvoicePaymentMethodOptionsAcssDebitMandateOptions),
    -- | verification_method: Bank account verification method.
    subscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod :: (GHC.Maybe.Maybe SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod')
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit' where
  toJSON obj = Data.Aeson.Types.Internal.object ("mandate_options" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsAcssDebit'MandateOptions obj : "verification_method" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod obj : GHC.Base.mempty)
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("mandate_options" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsAcssDebit'MandateOptions obj) GHC.Base.<> ("verification_method" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod obj))

instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit' where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "SubscriptionsResourcePaymentMethodOptionsAcssDebit'" (\obj -> (GHC.Base.pure SubscriptionsResourcePaymentMethodOptionsAcssDebit' GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "mandate_options")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "verification_method"))

-- | Create a new 'SubscriptionsResourcePaymentMethodOptionsAcssDebit'' with all required fields.
mkSubscriptionsResourcePaymentMethodOptionsAcssDebit' :: SubscriptionsResourcePaymentMethodOptionsAcssDebit'
mkSubscriptionsResourcePaymentMethodOptionsAcssDebit' =
  SubscriptionsResourcePaymentMethodOptionsAcssDebit'
    { subscriptionsResourcePaymentMethodOptionsAcssDebit'MandateOptions = GHC.Maybe.Nothing,
      subscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod = GHC.Maybe.Nothing
    }

-- | Defines the enum schema located at @components.schemas.subscriptions_resource_payment_method_options.properties.acss_debit.anyOf.properties.verification_method@ in the specification.
--
-- Bank account verification method.
data SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"automatic"@
    SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'EnumAutomatic
  | -- | Represents the JSON value @"instant"@
    SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'EnumInstant
  | -- | Represents the JSON value @"microdeposits"@
    SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'EnumMicrodeposits
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod' where
  toJSON (SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'Other val) = val
  toJSON (SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'EnumAutomatic) = "automatic"
  toJSON (SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'EnumInstant) = "instant"
  toJSON (SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'EnumMicrodeposits) = "microdeposits"

instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod' where
  parseJSON val =
    GHC.Base.pure
      ( if
            | val GHC.Classes.== "automatic" -> SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'EnumAutomatic
            | val GHC.Classes.== "instant" -> SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'EnumInstant
            | val GHC.Classes.== "microdeposits" -> SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'EnumMicrodeposits
            | GHC.Base.otherwise -> SubscriptionsResourcePaymentMethodOptionsAcssDebit'VerificationMethod'Other val
      )

-- | Defines the object schema located at @components.schemas.subscriptions_resource_payment_method_options.properties.bancontact.anyOf@ in the specification.
--
-- This sub-hash contains details about the Bancontact payment method options to pass to invoices created by the subscription.
data SubscriptionsResourcePaymentMethodOptionsBancontact' = SubscriptionsResourcePaymentMethodOptionsBancontact'
  { -- | preferred_language: Preferred language of the Bancontact authorization page that the customer is redirected to.
    subscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage :: (GHC.Maybe.Maybe SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage')
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionsResourcePaymentMethodOptionsBancontact' where
  toJSON obj = Data.Aeson.Types.Internal.object ("preferred_language" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage obj : GHC.Base.mempty)
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs ("preferred_language" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage obj)

instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionsResourcePaymentMethodOptionsBancontact' where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "SubscriptionsResourcePaymentMethodOptionsBancontact'" (\obj -> GHC.Base.pure SubscriptionsResourcePaymentMethodOptionsBancontact' GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "preferred_language"))

-- | Create a new 'SubscriptionsResourcePaymentMethodOptionsBancontact'' with all required fields.
mkSubscriptionsResourcePaymentMethodOptionsBancontact' :: SubscriptionsResourcePaymentMethodOptionsBancontact'
mkSubscriptionsResourcePaymentMethodOptionsBancontact' = SubscriptionsResourcePaymentMethodOptionsBancontact' {subscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage = GHC.Maybe.Nothing}

-- | Defines the enum schema located at @components.schemas.subscriptions_resource_payment_method_options.properties.bancontact.anyOf.properties.preferred_language@ in the specification.
--
-- Preferred language of the Bancontact authorization page that the customer is redirected to.
data SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"de"@
    SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumDe
  | -- | Represents the JSON value @"en"@
    SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumEn
  | -- | Represents the JSON value @"fr"@
    SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumFr
  | -- | Represents the JSON value @"nl"@
    SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumNl
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage' where
  toJSON (SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'Other val) = val
  toJSON (SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumDe) = "de"
  toJSON (SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumEn) = "en"
  toJSON (SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumFr) = "fr"
  toJSON (SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumNl) = "nl"

instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage' where
  parseJSON val =
    GHC.Base.pure
      ( if
            | val GHC.Classes.== "de" -> SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumDe
            | val GHC.Classes.== "en" -> SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumEn
            | val GHC.Classes.== "fr" -> SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumFr
            | val GHC.Classes.== "nl" -> SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'EnumNl
            | GHC.Base.otherwise -> SubscriptionsResourcePaymentMethodOptionsBancontact'PreferredLanguage'Other val
      )

-- | Defines the object schema located at @components.schemas.subscriptions_resource_payment_method_options.properties.card.anyOf@ in the specification.
--
-- This sub-hash contains details about the Card payment method options to pass to invoices created by the subscription.
data SubscriptionsResourcePaymentMethodOptionsCard' = SubscriptionsResourcePaymentMethodOptionsCard'
  { -- | request_three_d_secure: We strongly recommend that you rely on our SCA Engine to automatically prompt your customers for authentication based on risk level and [other requirements](https:\/\/stripe.com\/docs\/strong-customer-authentication). However, if you wish to request 3D Secure based on logic from your own fraud engine, provide this option. Read our guide on [manually requesting 3D Secure](https:\/\/stripe.com\/docs\/payments\/3d-secure\#manual-three-ds) for more information on how this configuration interacts with Radar and our SCA Engine.
    subscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure :: (GHC.Maybe.Maybe SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure')
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionsResourcePaymentMethodOptionsCard' where
  toJSON obj = Data.Aeson.Types.Internal.object ("request_three_d_secure" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure obj : GHC.Base.mempty)
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs ("request_three_d_secure" Data.Aeson.Types.ToJSON..= subscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure obj)

instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionsResourcePaymentMethodOptionsCard' where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "SubscriptionsResourcePaymentMethodOptionsCard'" (\obj -> GHC.Base.pure SubscriptionsResourcePaymentMethodOptionsCard' GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "request_three_d_secure"))

-- | Create a new 'SubscriptionsResourcePaymentMethodOptionsCard'' with all required fields.
mkSubscriptionsResourcePaymentMethodOptionsCard' :: SubscriptionsResourcePaymentMethodOptionsCard'
mkSubscriptionsResourcePaymentMethodOptionsCard' = SubscriptionsResourcePaymentMethodOptionsCard' {subscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure = GHC.Maybe.Nothing}

-- | Defines the enum schema located at @components.schemas.subscriptions_resource_payment_method_options.properties.card.anyOf.properties.request_three_d_secure@ in the specification.
--
-- We strongly recommend that you rely on our SCA Engine to automatically prompt your customers for authentication based on risk level and [other requirements](https:\/\/stripe.com\/docs\/strong-customer-authentication). However, if you wish to request 3D Secure based on logic from your own fraud engine, provide this option. Read our guide on [manually requesting 3D Secure](https:\/\/stripe.com\/docs\/payments\/3d-secure\#manual-three-ds) for more information on how this configuration interacts with Radar and our SCA Engine.
data SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"any"@
    SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'EnumAny
  | -- | Represents the JSON value @"automatic"@
    SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'EnumAutomatic
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure' where
  toJSON (SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'Other val) = val
  toJSON (SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'EnumAny) = "any"
  toJSON (SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'EnumAutomatic) = "automatic"

instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure' where
  parseJSON val =
    GHC.Base.pure
      ( if
            | val GHC.Classes.== "any" -> SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'EnumAny
            | val GHC.Classes.== "automatic" -> SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'EnumAutomatic
            | GHC.Base.otherwise -> SubscriptionsResourcePaymentMethodOptionsCard'RequestThreeDSecure'Other val
      )
