module StripeAPI.Types.SubscriptionPaymentMethodOptionsCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SubscriptionPaymentMethodOptionsCard
instance Show SubscriptionPaymentMethodOptionsCard
instance Eq SubscriptionPaymentMethodOptionsCard
instance FromJSON SubscriptionPaymentMethodOptionsCard
instance ToJSON SubscriptionPaymentMethodOptionsCard
data SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'
instance Show SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'
instance Eq SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'
instance FromJSON SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'
instance ToJSON SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'
